-- AlterTable
ALTER TABLE "CourseEvent" ADD COLUMN     "earlyBirdCutoffDays" INTEGER NOT NULL DEFAULT 30,
ADD COLUMN     "earlyBirdPrice" DECIMAL(65,30) NOT NULL DEFAULT 499,
ADD COLUMN     "flatRate" DECIMAL(65,30) NOT NULL DEFAULT 10000,
ADD COLUMN     "hostKickbackPerHead" DECIMAL(65,30) NOT NULL DEFAULT 50,
ADD COLUMN     "maxAttendees" INTEGER NOT NULL DEFAULT 30,
ADD COLUMN     "minAttendees" INTEGER NOT NULL DEFAULT 8,
ADD COLUMN     "standardPrice" DECIMAL(65,30) NOT NULL DEFAULT 599;
